[package]
name = "fractal"
version = "0.0.1"
authors = ["Julian Sparber <julian@sparber.net>"]
edition = "2018"

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[dependencies]
async-stream = "0.3"
log = "0.4"
mime = "0.3.16"
tracing-subscriber = "0.3"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gtk-macros = "0.3"
once_cell = "1.5"
serde = "1.0.130"
serde_json = "1.0"
tokio = { version = "1.15", features = ["rt", "rt-multi-thread", "sync"] }
url = "2.2"
secret-service = "2.0"
html2pango = "0.4"
futures = "0.3"
rand = "0.8"
indexmap = "1.6.2"
qrcode = "0.12.0"
ashpd = { version = "0.2.0-beta-1", features = [
    "feature_gtk4",
    "feature_pipewire",
    "log",
] }
gst = { version = "0.18", package = "gstreamer" }
gst_base = { version = "0.18", package = "gstreamer-base" }
gst_video = { version = "0.18", package = "gstreamer-video" }
gst_player = { version = "0.18", package = "gstreamer-player" }
gst_gtk = { version = "0.1.0", package = "gst-plugin-gtk4" }
image = { version = "0.23", default-features = false, features = ["png"] }
regex = "1.5.4"
mime_guess = "2.0.3"
num_enum = "0.5.6"

[dependencies.sourceview]
package = "sourceview5"
version = "0.4.0"

[dependencies.gtk]
package = "gtk4"
version = "0.4.4"
features = ["v4_6"]

[dependencies.adw]
package = "libadwaita"
version = "0.1.0"

[dependencies.matrix-sdk]
git = "https://github.com/jsparber/matrix-rust-sdk.git"
branch = "enable_ruma_unstable_pre_spec"
features = [
    "socks",
    "encryption",
    "sled_cryptostore",
    "sled_state_store",
    "markdown",
]
